kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: notes-app-hpa
  namespace: dev
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-deployment
    apiVersion: apps/v1

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
