kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: my-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
  storageClassName: local-storage    
   
