kind: Service
apiVersion: v1
metadata:
  name: my-svc
  namespace: dev
  labels:
    app: myapp
spec:
  selector:
      app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer   
