kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-role-binding
  namespace: apache-ns

subjects:
- kind: User
  name: apache-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: apache-role
    apiGroup: rbac.authorization.k8s.io
